# Jekyll settings
permalink: pretty
markdown: kramdown

# Blog settings
name: Umair Khalil
authorname: Umair Khalil
description: Personal site of Umair Khalil, software developer.
url: http://umairkhalil.github.io

