# Jekyll settings
permalink: pretty
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        css_class: 'highlight'

# Blog settings
name: Umair Khalil
authorname: Umair Khalil
description: Personal site of Umair Khalil, software developer.
url: http://umairkhalil.github.io

